# Generated by Django 5.2.8 on 2025-11-11 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='herramienta',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='herramienta',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas_fotos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('TECNICO', 'tecnico')], default='OPERADOR', max_length=20),
        ),
        migrations.CreateModel(
            name='RegistroUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('BUENO', 'Bueno'), ('MALO', 'Malo'), ('REPARACION', 'En Reparación')], default='BUENO', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='uso_fotos/')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.herramienta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
